# Shared metadata for build-profile generation. Desktop Python tools read the
# same CSV directly; keep implementation source selection in render_core_sources.
set(_jellyframe_render_core_registry_file
    "${CMAKE_CURRENT_LIST_DIR}/render_core_feature_registry.csv")
if(NOT EXISTS "${_jellyframe_render_core_registry_file}")
    message(FATAL_ERROR "Render Core feature registry is missing: ${_jellyframe_render_core_registry_file}")
endif()

file(STRINGS "${_jellyframe_render_core_registry_file}" _jellyframe_render_core_registry_lines)
set(JELLYFRAME_RENDER_CORE_FEATURE_IDS)
foreach(_jellyframe_render_core_registry_line IN LISTS _jellyframe_render_core_registry_lines)
    string(STRIP "${_jellyframe_render_core_registry_line}" _jellyframe_render_core_registry_line)
    if(_jellyframe_render_core_registry_line STREQUAL "" OR
       _jellyframe_render_core_registry_line MATCHES "^#")
        continue()
    endif()
    string(REPLACE "|" ";" _jellyframe_render_core_registry_fields
        "${_jellyframe_render_core_registry_line}")
    list(LENGTH _jellyframe_render_core_registry_fields _jellyframe_render_core_registry_field_count)
    if(NOT _jellyframe_render_core_registry_field_count EQUAL 5)
        message(FATAL_ERROR "Malformed Render Core feature registry row: ${_jellyframe_render_core_registry_line}")
    endif()
    list(GET _jellyframe_render_core_registry_fields 0 _jellyframe_render_core_feature_id)
    list(GET _jellyframe_render_core_registry_fields 1 _jellyframe_render_core_dependencies)
    list(GET _jellyframe_render_core_registry_fields 2 _jellyframe_render_core_option)
    list(GET _jellyframe_render_core_registry_fields 3 _jellyframe_render_core_suffix)
    list(GET _jellyframe_render_core_registry_fields 4 _jellyframe_render_core_order)
    list(FIND JELLYFRAME_RENDER_CORE_FEATURE_IDS "${_jellyframe_render_core_feature_id}" _jellyframe_render_core_existing_index)
    if(NOT _jellyframe_render_core_existing_index EQUAL -1)
        message(FATAL_ERROR "Duplicate Render Core feature registry ID: ${_jellyframe_render_core_feature_id}")
    endif()
    foreach(_jellyframe_render_core_field IN ITEMS
            _jellyframe_render_core_dependencies _jellyframe_render_core_option _jellyframe_render_core_suffix)
        if("${${_jellyframe_render_core_field}}" STREQUAL "-")
            set(${_jellyframe_render_core_field} "")
        endif()
    endforeach()
    if(NOT _jellyframe_render_core_order MATCHES "^[0-9]+$")
        message(FATAL_ERROR "Render Core feature registry order must be numeric: ${_jellyframe_render_core_feature_id}")
    endif()
    string(MAKE_C_IDENTIFIER "${_jellyframe_render_core_feature_id}" _jellyframe_render_core_feature_key)
    set("JELLYFRAME_RENDER_CORE_FEATURE_${_jellyframe_render_core_feature_key}_OPTION" "${_jellyframe_render_core_option}")
    set("JELLYFRAME_RENDER_CORE_FEATURE_${_jellyframe_render_core_feature_key}_SUFFIX" "${_jellyframe_render_core_suffix}")
    set("JELLYFRAME_RENDER_CORE_FEATURE_${_jellyframe_render_core_feature_key}_ORDER" "${_jellyframe_render_core_order}")
    list(APPEND JELLYFRAME_RENDER_CORE_FEATURE_IDS "${_jellyframe_render_core_feature_id}")
endforeach()

function(jellyframe_render_core_feature_metadata feature field output)
    string(MAKE_C_IDENTIFIER "${feature}" _jellyframe_render_core_feature_key)
    set(_jellyframe_render_core_metadata_variable
        "JELLYFRAME_RENDER_CORE_FEATURE_${_jellyframe_render_core_feature_key}_${field}")
    set(${output} "${${_jellyframe_render_core_metadata_variable}}" PARENT_SCOPE)
endfunction()

function(jellyframe_render_core_enabled_features output)
    set(_jellyframe_render_core_enabled_features)
    foreach(_jellyframe_render_core_feature IN LISTS JELLYFRAME_RENDER_CORE_FEATURE_IDS)
        jellyframe_render_core_feature_metadata("${_jellyframe_render_core_feature}" OPTION _jellyframe_render_core_option)
        if(_jellyframe_render_core_option STREQUAL "")
            list(APPEND _jellyframe_render_core_enabled_features "${_jellyframe_render_core_feature}")
        elseif(NOT DEFINED ${_jellyframe_render_core_option})
            message(FATAL_ERROR "Render Core feature option is not defined: ${_jellyframe_render_core_option}")
        elseif(${_jellyframe_render_core_option})
            list(APPEND _jellyframe_render_core_enabled_features "${_jellyframe_render_core_feature}")
        endif()
    endforeach()
    set(${output} "${_jellyframe_render_core_enabled_features}" PARENT_SCOPE)
endfunction()
